#pragma once
#include "Global.h"
#include "State.h"

//DEFINE_STATE(XXState)和END_DEFINE_STATE定义XXState，之间定义个性化参数

DEFINE_STATE(StartState)
END_DEFINE_STATE

DEFINE_STATE(InitState)
END_DEFINE_STATE

DEFINE_STATE(WaitActionState)
END_DEFINE_STATE

DEFINE_STATE(ProcessState)
END_DEFINE_STATE

DEFINE_STATE(GameOverState)
END_DEFINE_STATE
